apiVersion: v1
kind: Service
metadata:
  name: {{ template "ethereum.fullname" . }}-bootnode-registrar-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "ethereum.name" . }}-bootnode-registrar-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    app: {{ template "ethereum.name" . }}-bootnode-registrar
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9898