apiVersion: v1
kind: Service
metadata:
  name: {{ template "ethereum.fullname" . }}-bootnode-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "ethereum.name" . }}-bootnode-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    app: {{ template "ethereum.name" . }}-bootnode
  clusterIP: None
  ports:
  - name: discovery
    port: 30301
    protocol: UDP
  - name: http
    port: 8080