apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ethereum.fullname" . }}-ethstats-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "ethereum.name" . }}-ethstats-secret
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
type: Opaque
data:
  WS_SECRET: {{ .Values.ethstats.webSocketSecret | b64enc | quote }}