apiVersion: v1
kind: Service
metadata:
  name: {{ template "ethereum.fullname" . }}-ethstats-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "ethereum.name" . }}-ethstats-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    app: {{ template "ethereum.name" . }}-ethstats
  type: {{ .Values.ethstats.service.type }}
  ports:
  - port: 80
    targetPort: http