apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ethereum.fullname" . }}-geth-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "ethereum.name" . }}-geth-config
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  networkid: "{{ .Values.geth.genesis.networkId }}"
  genesis.json: |-
    {
        "config": {
            "chainId": {{ .Values.geth.genesis.networkId }},
            "homesteadBlock": 0,
            "eip150Block": 0,
            "eip155Block": 0,
            "eip158Block": 0
        },
        "difficulty": "0x2000",
        "gasLimit": "8000000000",
        "alloc": {
            {{- range .Values.geth.genesis.accountsToFund }}
            {{ . | quote }}: 
            {
                "balance": "500000000000000000000"
            }
            {{- end }}
        }
    }

    