apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ethereum.fullname" . }}-geth-miner-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "ethereum.name" . }}-geth-miner-secret
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
type: Opaque
data:
  accountsecret: {{ .Values.geth.miner.account.secret | b64enc | quote }}